server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
      hostname: discover
      instance-id: ${spring.application.name}:${server.port}
  server:
    enable-self-preservation: false # 关闭自我保护（自我保护就是不注销微服务）
    eviction-interval-timer-in-ms: 60000 # 清理（无效节点）间隔 默认60*1000毫秒