server:
  port: 8020
spring:
  application:
    name: microservice-config-server # 指定注册到eureka server上的应用名称
  cloud:
    config:
      server:
        git:
          # 配置Git仓库地址
          uri: https://github.com/JesseyGone/config-repo.git
          # Git仓库账号
          username: 673350601@qq.com
          # Git仓库密码
          password: 我的github密码会告诉你？
          # 搜索目录，Git仓库子目录
          search-paths: config*