server:
  port: 8010
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
user:
  userServiceUrl: http://localhost:8000/user/
spring:
  application:
    name: microservice-consumer-user # 指定注册到eureka server上的应用名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true # 开启健康检查 - 需要spring-boot-starter-actuator依赖
  instance:
    prefer-ip-address: true # 将自己的IP注册到eureka server，如果为false（默认），则注册的是hostname
    lease-renewal-interval-in-seconds: 30 # 续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 90 # 续约到期时间（默认90秒）