server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
      hostname: peer1
      instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/