server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
      hostname: peer2
      instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/